* LaTeX Beamer template for the [[http://ihs.ac.at/][IHS]]

This template is not official, and is under development.

** License

All files and designs are copyright Institut für Höhere Studien (Institute for Advanced Studies, Vienna) and may not be used without permission.

** Installation

You need to make the files of the template available to your local TeX installation.  For most people, installing in their home directory is the easiest solution.

Executing
#+BEGIN_SRC shell
kpsewhich -var-value TEXMFHOME
#+END_SRC
in the command line will tell you your TeX home directory, which is usually =~/texmf/= or something similar.  You might want to make a subdirectory inside that to keep things tidy, eg
#+BEGIN_SRC shell
mkdir -p ~/texmf/tex/latex/beamer/
#+END_SRC
Then you can
#+BEGIN_SRC shell
cd ~/texmf/tex/latex/beamer/
#+END_SRC
and get the template following one of the two options below.  You may have to run =mktexlsr= after getting the source and after updating.

*** Git

This is the suggested method, since it makes it very easy to keep up with changes to the template.  If you don't have [[http://git-scm.com/][git]], you need to install it, then execute
#+BEGIN_SRC shell
git clone git://github.com/tpapp/ihs-beamer.git
#+END_SRC
and you are done.  If you want to check for updates, just switch to the appropriate directory and execute
#+BEGIN_SRC shell
git pull origin master
#+END_SRC

*** Zip/tar archive

Available on [[https://github.com/tpapp/ihs-beamer/zipball/master][Github]].

* Usage

For the entire theme:
#+BEGIN_SRC LaTeX
\usetheme{ihs}
#+END_SRC

For just the colors:
#+BEGIN_SRC LaTeX
\usecolortheme{ihs}
#+END_SRC

You can use two commands for generating logos, =\IHSlogo= and =\IHSlogotext=, the first is with text and the latter is without.  Both accept an optional argument that is passed on to =\includegraphics=.

There is an example available, see =example.tex=.

* Bugs/suggestions

Please report them via [[https://github.com/tpapp/ihs-beamer/issues][Github]].
